name: music_player
description: An app to play your local music
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  mockito: 5.3.2
  marquee: 2.2.3
  sqflite: ^2.1.0+1
  audioplayers: ^1.1.1
  file_picker: ^5.2.2
  path: ^1.8.2
  get_it: ^7.2.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
